name: Build Tares Server
description: Builds the server and it's artifacts that's upload to the bin folder

inputs:
    artifact-name:
        description: Name given to the built server artifact to be uploaded, default to bin/
        required: false
        default: client

# composite reusable action
runs:
    using: composite
    steps:
        - name: Build artifacts
          shell: bash
          run: |
              mkdir -p bin
              go build -o bin/${{inputs.artifact-name}} ./client/main.go
